### ISSUE TITLE
only use wayland, x11-fallback

### ISSUE THREAD

**Issue by SnuggleCovenant** [flathub/org.js.nuclear.Nuclear#12]
this issue is meant to track the removal of the **legacy window warning**. as soon as possible, nuclear must launch in wayland, with an x11-fallback for x11 users, instead of only launching in x11.

You can read the warnings on the flathub page https://flathub.org/apps/org.js.nuclear.Nuclear

It's been working as well on my end as using the x11 socket. I used flatseal to enable wayland and uncheck x11.

However, nvidia dropped a new driver for my video card recently. This new driver is a significant upgrade in capabilities on linux. Since installed, 545 is making electron apps flicker and visually glitch on wayland. perhaps this new nvidia driver introduced a new need for accomodation in the app's code to prevent the flickering? perhaps it requires attention upstream?

I would however suspect that AMD and Intel graphics users would currently be unbothered (as I was before this nvidia update).

**Comment by nukeop** [comment]
"Must"?

**Comment by SnuggleCovenant** [comment]
I don't feel that you are receptive to the work I've spent writing a very comprehensive issue with your one word retort, and your opinionated response on the previous issue i posted. I will simply unfollow these. Sorry for the trouble.
