### ISSUE TITLE
restrict file access to a single directory

### ISSUE THREAD

**Issue by SnuggleCovenant** [flathub/org.js.nuclear.Nuclear#13]
nuclear shows a prohibitive warning on the subject of the full ~ folder access which would include the downloads folder, pictures, documents, all of which are irrelevant.

you can view the warning here https://flathub.org/apps/org.js.nuclear.Nuclear

a good fix might be to download to, and read from, a folder specifically.
e.g. ~/Music/nuclear/

**Comment by nukeop** [comment]
That sounds like it would unnecessarily restrict access for no reason. Many people like reading their local music from many different folders. This is how most programs work on Linux, and have been working on Linux for decades. I see no problem here.

**Comment by SnuggleCovenant** [comment]
using for an argument that something has always happened is an appeal to tradition, which is a type of fallacy. in this case, I don't think an appeal to tradition is pertinent.

there has been malware in open sourced projects in general before, and there will be again in the future. I don't imagine the chance of that happening with nuclear itself is highly probable. This issue might be more fitting an enhancement than a problem depending on how you view things.

home includes sensitive files such as .bashrc, documents, pictures, so on. all these a user would want to protect for different valid reasons.

with that said, it might be a good idea to have a hollistic approach. to go inline with the flatpak philosophy of restraining an app to what it needs and nothing else.

removing the warning signs will attract cautious users.

better to be safe and err on the side of caution. belts and suspenders. layered defense. that sort of thing.
